language:
  - swift
  
osx_image:
- xcode12

# reference: https://docs.travis-ci.com/user/reference/osx/#xcode-12
env:
  matrix:
    exclude:
      - osx_image: xcode12
      - TEST_SDK=iphoneos14.0 OS=14.0 NAME='iPhone 11 Pro Max'
      - TEST_SDK=iphoneos10.3 OS=10.3 NAME='iPhone 8 Plus'
      - TEST_SDK=iphonesimulator13.5 OS=13.5 NAME='iPhone 11 Pro'
      - TEST_SDK=iphonesimulator11.4 OS=11.4 NAME='iPhone 8'
      
branches:
  only:
  - master

script:
  - xcodebuild -project EasyAlbum.xcodeproj -scheme EasyAlbum -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

after_success:
  #- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - ray00178@gmail.com
      - brave2risks@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
