language:
  - swift
  
osx_image:
- xcode11

env:
  matrix:
    exclude:
      - osx_image: xcode11
      - TEST_SDK=iphonesimulator13.0 OS=12.1 NAME='iPhone 11 Pro Max'
      - TEST_SDK=iphonesimulator13.0 OS=13.0 NAME='iPhone 11 Pro'
      - TEST_SDK=iphonesimulator13.0 OS=13.0 NAME='iPhone 8 Plus'
      - TEST_SDK=iphonesimulator13.0 OS=13.0 NAME='iPhone 8'
      
branches:
  only:
  - master

script:
  - xcodebuild -project EasyAlbum.xcodeproj -scheme EasyAlbum -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

after_success:
  #- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - ray00178@gmail.com
      - brave2risks@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
